model:
  type: origin
  path: Qwen/Qwen2-0.5B-Instruct
  base: 1000000
  distance_scale: 1.0
  fattn: false
  # rag model
  is_rag: true

max_len: 32768
chunk_size: 2048
conv_type: qwen
truncation: suffix